"""
This type stub file was generated by pyright.
"""

"""
Implements auth methods
"""
SCRAMBLE_LENGTH = ...
sha1_new = ...

def scramble_native_password(password, message):  # -> bytes:
    """Scramble used for mysql_native_password"""
    ...

_nacl_bindings = ...

def ed25519_password(password, scramble):
    """Sign a random scramble with elliptic curve Ed25519.

    Secret and public key are derived from password.
    """
    ...

def sha2_rsa_encrypt(password, salt, public_key):  # -> Any:
    """
    Encrypt password with salt and public_key.

    Used for sha256_password and caching_sha2_password.
    """
    ...

async def sha256_password_auth(conn, pkt): ...
def scramble_caching_sha2(password, nonce):  # -> bytes:
    """Scramble algorithm used in cached_sha2_password fast path.

    XOR(SHA256(password), SHA256(SHA256(SHA256(password)), nonce))
    """
    ...

async def caching_sha2_password_auth(conn, pkt):  # -> None:
    ...
