import typing

from .cursor import Cursor

_C = typing.TypeVar("_C", bound=Cursor)

class Connection:
    @typing.overload
    def cursor(self, cursor: None = ...) -> typing.AsyncContextManager[Cursor]: ...
    @typing.overload
    def cursor(self, cursor: _C) -> typing.AsyncContextManager[_C]: ...
    def cursor(self, cursor: _C | None = ...) -> typing.AsyncContextManager[_C]: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
