import typing

class Cursor:
    async def execute(self, query: str, args: typing.Any) -> int: ...
    async def fetchall(self) -> typing.Sequence[tuple[typing.Any, ...]]: ...
    async def fetchone(self) -> tuple[typing.Any, ...]: ...
