"""
This type stub file was generated by pyright.
"""

from configparser import RawConfigParser

class Parser(RawConfigParser):
    def __init__(self, **kwargs) -> None: ...
    def get(self, section, option, **kwargs):  # -> str | Any:
        ...
