"""
This type stub file was generated by pyright.
"""

class Column:
    """Definition of a column"""

    def __init__(self, column_type, column_schema, packet) -> None: ...
    @property
    def data(self):  # -> dict[str, Any]:
        ...
