"""
This type stub file was generated by pyright.
"""

class Table:
    def __init__(
        self,
        column_schemas,
        table_id,
        schema: str,
        table: str,
        columns,
        primary_key=...,
    ) -> None: ...
    @property
    def data(self):  # -> dict[str, Any]:
        ...
